application:
    data_path: signalappdata/
    max-page-size: 25
    max-name-length: 100
    min-password-length: 5
    user-idle-timeout: 3600
    verify-captcha: true
    secure-random-seed: ${SECURE_RANDOM_SEED}
    limits:
        max-signal-length: 1024000
        max-user-signals-number: 50
        max-user-folders-number: 10
        extended-storage-multiplier: 5
mailing:
    password: ${MAILING_PASSWORD}
    smtp-port: ${MAILING_SMTP_PORT}
    smtp-host: ${MAILING_SMTP_HOST}
    username: ${MAILING_USERNAME}
recaptcha:
    secret: ${RECAPTCHA_SECRET}
    url: https://www.google.com/recaptcha/api/siteverify
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USERNAME}
    flyway:
        locations: classpath:db/migration
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        open-in-view: false
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
    security:
        user:
            password: ${SECURITY_USER_PASSWORD}
