version: '3.8'

services:

  signalapp:
    build:
      context: ./images/app
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - signalapp-postgres
    environment:
      DB_URL: jdbc:postgresql://signalapp-postgres:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      MAILING_SMTP_HOST: smtp.mail.ru
      MAILING_SMTP_PORT: 587
      SECURITY_USER_PASSWORD: password
    env_file: ./secrets/secrets.env
    volumes:
      - ../../target/signalapp-1.3.0.jar:/signalapp/signalapp.jar
      - ../../../signalappdata/:/signalapp/signalappdata
    stdin_open: true
    tty: true
    networks:
      signalapp-net:

  signalapp-postgres:
    image: postgres:14.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      signalapp-net:

  signalapp-frontend:
    build:
      context: ./images/frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ../../frontend/:/frontend
    networks:
      signalapp-net:

  signalapp-nginx:
    image: nginx:1.23-alpine
    ports:
      - '80:80'
    depends_on:
      - signalapp
      - signalapp-frontend
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../nginx/mime.types:/etc/nginx/mime.types
      - ../../frontend-old/:/usr/share/nginx/static
    networks:
      signalapp-net:

networks:
  signalapp-net:
