version: '3'

services:

  signalapp:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - signalapp-postgres
    volumes:
      - ../../:/signalapp
      - ../../../signalappres/:/signalapp/signalappres
      - ../../../signalapp-frontend/.output/public/:/signalapp/signalapp-frontend
      - ../../../signalappdata/:/signalapp/signalappdata
    stdin_open: true
    tty: true
    networks:
      signalapp-net:

  signalapp-postgres:
    image: postgres:14.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      signalapp-net:

networks:
  signalapp-net: